name: publish 

on:
workflow_dispatch:

push:
branches:
-main

job:
 publish:
 run-on: ubuntu-latest
 
 steps: 
   - uses: actions/checkout@v3
   
   -name: setup.NET
    uses: actions.setup
    whith: dotnet-version: '6.0.x'
    
    -name: restore 
     -run: dotnet restore ./LeetCode.sln
     
     name: build
     run: dotnet build ./LeetCode.sln confiugration release --no-restore 
     name: publish
     run: dotnet publish ./LeetCode.sln -configuration release --no-build
     
     
  
